vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        category_file:
            uri_prefix: /uploads/images/category
            upload_destination: '%upload_directory%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            
        decision_file:
            uri_prefix: /uploads/images/decision
            upload_destination: '%upload_directory%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer